// Code generated by 'yaegi extract github.com/alist-org/alist/v3/drivers/base'. DO NOT EDIT.

package lib

import (
	"github.com/alist-org/alist/v3/drivers/base"
	"reflect"
)

func init() {
	Symbols["github.com/alist-org/alist/v3/drivers/base/base"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultTimeout":   reflect.ValueOf(&base.DefaultTimeout).Elem(),
		"HandleRange":      reflect.ValueOf(base.HandleRange),
		"HttpClient":       reflect.ValueOf(&base.HttpClient).Elem(),
		"NewRestyClient":   reflect.ValueOf(base.NewRestyClient),
		"NoRedirectClient": reflect.ValueOf(&base.NoRedirectClient).Elem(),
		"RestyClient":      reflect.ValueOf(&base.RestyClient).Elem(),
		"UserAgent":        reflect.ValueOf(&base.UserAgent).Elem(),

		// type definitions
		"Json":        reflect.ValueOf((*base.Json)(nil)),
		"ReqCallback": reflect.ValueOf((*base.ReqCallback)(nil)),
		"TokenResp":   reflect.ValueOf((*base.TokenResp)(nil)),
	}
}
