// Code generated by 'yaegi extract github.com/alist-org/alist/v3/internal/model'. DO NOT EDIT.

package lib

import (
	"github.com/alist-org/alist/v3/internal/model"
	"go/constant"
	"go/token"
	"io"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/alist-org/alist/v3/internal/model/model"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ADMIN":               reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"ARIA2":               reflect.ValueOf(constant.MakeFromLiteral("5", token.INT, 0)),
		"DEPRECATED":          reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"ExtractFolder":       reflect.ValueOf(model.ExtractFolder),
		"GENERAL":             reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"GLOBAL":              reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"GUEST":               reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"GetThumb":            reflect.ValueOf(model.GetThumb),
		"GetUrl":              reflect.ValueOf(model.GetUrl),
		"INDEX":               reflect.ValueOf(constant.MakeFromLiteral("6", token.INT, 0)),
		"MaxInt":              reflect.ValueOf(model.MaxInt),
		"MaxUint":             reflect.ValueOf(model.MaxUint),
		"MinInt":              reflect.ValueOf(model.MinInt),
		"MinUint":             reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"NewObjMerge":         reflect.ValueOf(model.NewObjMerge),
		"PLUGIN_MODE_DRPC":    reflect.ValueOf(constant.MakeFromLiteral("\"drpc\"", token.STRING, 0)),
		"PLUGIN_MODE_WASI":    reflect.ValueOf(constant.MakeFromLiteral("\"wasi\"", token.STRING, 0)),
		"PLUGIN_MODE_YAEGI":   reflect.ValueOf(constant.MakeFromLiteral("\"yaegi\"", token.STRING, 0)),
		"PLUGIN_TYPE_STORAGE": reflect.ValueOf(constant.MakeFromLiteral("\"storage\"", token.STRING, 0)),
		"PREVIEW":             reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"PRIVATE":             reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"PUBLIC":              reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"READONLY":            reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"SINGLE":              reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"SITE":                reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"SSO":                 reflect.ValueOf(constant.MakeFromLiteral("7", token.INT, 0)),
		"STYLE":               reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"SortFiles":           reflect.ValueOf(model.SortFiles),
		"UnwrapObj":           reflect.ValueOf(model.UnwrapObj),
		"WrapObjName":         reflect.ValueOf(model.WrapObjName),
		"WrapObjsName":        reflect.ValueOf(model.WrapObjsName),

		// type definitions
		"FileStream":          reflect.ValueOf((*model.FileStream)(nil)),
		"FileStreamer":        reflect.ValueOf((*model.FileStreamer)(nil)),
		"FsOtherArgs":         reflect.ValueOf((*model.FsOtherArgs)(nil)),
		"IndexProgress":       reflect.ValueOf((*model.IndexProgress)(nil)),
		"Link":                reflect.ValueOf((*model.Link)(nil)),
		"LinkArgs":            reflect.ValueOf((*model.LinkArgs)(nil)),
		"ListArgs":            reflect.ValueOf((*model.ListArgs)(nil)),
		"Meta":                reflect.ValueOf((*model.Meta)(nil)),
		"Obj":                 reflect.ValueOf((*model.Obj)(nil)),
		"ObjMerge":            reflect.ValueOf((*model.ObjMerge)(nil)),
		"ObjThumb":            reflect.ValueOf((*model.ObjThumb)(nil)),
		"ObjThumbURL":         reflect.ValueOf((*model.ObjThumbURL)(nil)),
		"ObjUnwrap":           reflect.ValueOf((*model.ObjUnwrap)(nil)),
		"ObjWrapName":         reflect.ValueOf((*model.ObjWrapName)(nil)),
		"Object":              reflect.ValueOf((*model.Object)(nil)),
		"ObjectURL":           reflect.ValueOf((*model.ObjectURL)(nil)),
		"OtherArgs":           reflect.ValueOf((*model.OtherArgs)(nil)),
		"PageReq":             reflect.ValueOf((*model.PageReq)(nil)),
		"Plugin":              reflect.ValueOf((*model.Plugin)(nil)),
		"PluginConfig":        reflect.ValueOf((*model.PluginConfig)(nil)),
		"PluginConfigHelper":  reflect.ValueOf((*model.PluginConfigHelper)(nil)),
		"PluginControl":       reflect.ValueOf((*model.PluginControl)(nil)),
		"PluginControlHelper": reflect.ValueOf((*model.PluginControlHelper)(nil)),
		"Proxy":               reflect.ValueOf((*model.Proxy)(nil)),
		"SearchNode":          reflect.ValueOf((*model.SearchNode)(nil)),
		"SearchReq":           reflect.ValueOf((*model.SearchReq)(nil)),
		"SetPath":             reflect.ValueOf((*model.SetPath)(nil)),
		"SettingItem":         reflect.ValueOf((*model.SettingItem)(nil)),
		"Sort":                reflect.ValueOf((*model.Sort)(nil)),
		"Storage":             reflect.ValueOf((*model.Storage)(nil)),
		"Thumb":               reflect.ValueOf((*model.Thumb)(nil)),
		"Thumbnail":           reflect.ValueOf((*model.Thumbnail)(nil)),
		"URL":                 reflect.ValueOf((*model.URL)(nil)),
		"Url":                 reflect.ValueOf((*model.Url)(nil)),
		"User":                reflect.ValueOf((*model.User)(nil)),

		// interface wrapper definitions
		"_FileStreamer":  reflect.ValueOf((*_github_com_alist_org_alist_v3_internal_model_FileStreamer)(nil)),
		"_Obj":           reflect.ValueOf((*_github_com_alist_org_alist_v3_internal_model_Obj)(nil)),
		"_ObjUnwrap":     reflect.ValueOf((*_github_com_alist_org_alist_v3_internal_model_ObjUnwrap)(nil)),
		"_PluginConfig":  reflect.ValueOf((*_github_com_alist_org_alist_v3_internal_model_PluginConfig)(nil)),
		"_PluginControl": reflect.ValueOf((*_github_com_alist_org_alist_v3_internal_model_PluginControl)(nil)),
		"_SetPath":       reflect.ValueOf((*_github_com_alist_org_alist_v3_internal_model_SetPath)(nil)),
		"_Thumb":         reflect.ValueOf((*_github_com_alist_org_alist_v3_internal_model_Thumb)(nil)),
		"_URL":           reflect.ValueOf((*_github_com_alist_org_alist_v3_internal_model_URL)(nil)),
	}
}

// _github_com_alist_org_alist_v3_internal_model_FileStreamer is an interface wrapper for FileStreamer type
type _github_com_alist_org_alist_v3_internal_model_FileStreamer struct {
	IValue         interface{}
	WClose         func() error
	WGetID         func() string
	WGetMimetype   func() string
	WGetName       func() string
	WGetOld        func() model.Obj
	WGetPath       func() string
	WGetReadCloser func() io.ReadCloser
	WGetSize       func() int64
	WIsDir         func() bool
	WModTime       func() time.Time
	WNeedStore     func() bool
	WRead          func(p []byte) (n int, err error)
	WSetReadCloser func(a0 io.ReadCloser)
}

func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) Close() error {
	return W.WClose()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) GetID() string {
	return W.WGetID()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) GetMimetype() string {
	return W.WGetMimetype()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) GetName() string {
	return W.WGetName()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) GetOld() model.Obj {
	return W.WGetOld()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) GetPath() string {
	return W.WGetPath()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) GetReadCloser() io.ReadCloser {
	return W.WGetReadCloser()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) GetSize() int64 {
	return W.WGetSize()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) IsDir() bool {
	return W.WIsDir()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) ModTime() time.Time {
	return W.WModTime()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) NeedStore() bool {
	return W.WNeedStore()
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _github_com_alist_org_alist_v3_internal_model_FileStreamer) SetReadCloser(a0 io.ReadCloser) {
	W.WSetReadCloser(a0)
}

// _github_com_alist_org_alist_v3_internal_model_Obj is an interface wrapper for Obj type
type _github_com_alist_org_alist_v3_internal_model_Obj struct {
	IValue   interface{}
	WGetID   func() string
	WGetName func() string
	WGetPath func() string
	WGetSize func() int64
	WIsDir   func() bool
	WModTime func() time.Time
}

func (W _github_com_alist_org_alist_v3_internal_model_Obj) GetID() string {
	return W.WGetID()
}
func (W _github_com_alist_org_alist_v3_internal_model_Obj) GetName() string {
	return W.WGetName()
}
func (W _github_com_alist_org_alist_v3_internal_model_Obj) GetPath() string {
	return W.WGetPath()
}
func (W _github_com_alist_org_alist_v3_internal_model_Obj) GetSize() int64 {
	return W.WGetSize()
}
func (W _github_com_alist_org_alist_v3_internal_model_Obj) IsDir() bool {
	return W.WIsDir()
}
func (W _github_com_alist_org_alist_v3_internal_model_Obj) ModTime() time.Time {
	return W.WModTime()
}

// _github_com_alist_org_alist_v3_internal_model_ObjUnwrap is an interface wrapper for ObjUnwrap type
type _github_com_alist_org_alist_v3_internal_model_ObjUnwrap struct {
	IValue  interface{}
	WUnwrap func() model.Obj
}

func (W _github_com_alist_org_alist_v3_internal_model_ObjUnwrap) Unwrap() model.Obj {
	return W.WUnwrap()
}

// _github_com_alist_org_alist_v3_internal_model_PluginConfig is an interface wrapper for PluginConfig type
type _github_com_alist_org_alist_v3_internal_model_PluginConfig struct {
	IValue         interface{}
	WGetApiVersion func() []string
	WGetName       func() string
	WGetType       func() []string
	WGetUUID       func() string
	WGetVersion    func() string
}

func (W _github_com_alist_org_alist_v3_internal_model_PluginConfig) GetApiVersion() []string {
	return W.WGetApiVersion()
}
func (W _github_com_alist_org_alist_v3_internal_model_PluginConfig) GetName() string {
	return W.WGetName()
}
func (W _github_com_alist_org_alist_v3_internal_model_PluginConfig) GetType() []string {
	return W.WGetType()
}
func (W _github_com_alist_org_alist_v3_internal_model_PluginConfig) GetUUID() string {
	return W.WGetUUID()
}
func (W _github_com_alist_org_alist_v3_internal_model_PluginConfig) GetVersion() string {
	return W.WGetVersion()
}

// _github_com_alist_org_alist_v3_internal_model_PluginControl is an interface wrapper for PluginControl type
type _github_com_alist_org_alist_v3_internal_model_PluginControl struct {
	IValue   interface{}
	WConfig  func() (model.PluginConfig, error)
	WLoad    func() error
	WRelease func() error
	WUnload  func() error
}

func (W _github_com_alist_org_alist_v3_internal_model_PluginControl) Config() (model.PluginConfig, error) {
	return W.WConfig()
}
func (W _github_com_alist_org_alist_v3_internal_model_PluginControl) Load() error {
	return W.WLoad()
}
func (W _github_com_alist_org_alist_v3_internal_model_PluginControl) Release() error {
	return W.WRelease()
}
func (W _github_com_alist_org_alist_v3_internal_model_PluginControl) Unload() error {
	return W.WUnload()
}

// _github_com_alist_org_alist_v3_internal_model_SetPath is an interface wrapper for SetPath type
type _github_com_alist_org_alist_v3_internal_model_SetPath struct {
	IValue   interface{}
	WSetPath func(path string)
}

func (W _github_com_alist_org_alist_v3_internal_model_SetPath) SetPath(path string) {
	W.WSetPath(path)
}

// _github_com_alist_org_alist_v3_internal_model_Thumb is an interface wrapper for Thumb type
type _github_com_alist_org_alist_v3_internal_model_Thumb struct {
	IValue interface{}
	WThumb func() string
}

func (W _github_com_alist_org_alist_v3_internal_model_Thumb) Thumb() string {
	return W.WThumb()
}

// _github_com_alist_org_alist_v3_internal_model_URL is an interface wrapper for URL type
type _github_com_alist_org_alist_v3_internal_model_URL struct {
	IValue interface{}
	WURL   func() string
}

func (W _github_com_alist_org_alist_v3_internal_model_URL) URL() string {
	return W.WURL()
}
