// Code generated by 'yaegi extract github.com/aws/aws-sdk-go/aws'. DO NOT EDIT.

package lib

import (
	"github.com/aws/aws-sdk-go/aws"
	"go/constant"
	"go/token"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/aws/aws-sdk-go/aws/aws"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BackgroundContext":           reflect.ValueOf(aws.BackgroundContext),
		"Bool":                        reflect.ValueOf(aws.Bool),
		"BoolMap":                     reflect.ValueOf(aws.BoolMap),
		"BoolSlice":                   reflect.ValueOf(aws.BoolSlice),
		"BoolValue":                   reflect.ValueOf(aws.BoolValue),
		"BoolValueMap":                reflect.ValueOf(aws.BoolValueMap),
		"BoolValueSlice":              reflect.ValueOf(aws.BoolValueSlice),
		"CopySeekableBody":            reflect.ValueOf(aws.CopySeekableBody),
		"ErrMissingEndpoint":          reflect.ValueOf(&aws.ErrMissingEndpoint).Elem(),
		"ErrMissingRegion":            reflect.ValueOf(&aws.ErrMissingRegion).Elem(),
		"Float32":                     reflect.ValueOf(aws.Float32),
		"Float32Map":                  reflect.ValueOf(aws.Float32Map),
		"Float32Slice":                reflect.ValueOf(aws.Float32Slice),
		"Float32Value":                reflect.ValueOf(aws.Float32Value),
		"Float32ValueMap":             reflect.ValueOf(aws.Float32ValueMap),
		"Float32ValueSlice":           reflect.ValueOf(aws.Float32ValueSlice),
		"Float64":                     reflect.ValueOf(aws.Float64),
		"Float64Map":                  reflect.ValueOf(aws.Float64Map),
		"Float64Slice":                reflect.ValueOf(aws.Float64Slice),
		"Float64Value":                reflect.ValueOf(aws.Float64Value),
		"Float64ValueMap":             reflect.ValueOf(aws.Float64ValueMap),
		"Float64ValueSlice":           reflect.ValueOf(aws.Float64ValueSlice),
		"Int":                         reflect.ValueOf(aws.Int),
		"Int16":                       reflect.ValueOf(aws.Int16),
		"Int16Map":                    reflect.ValueOf(aws.Int16Map),
		"Int16Slice":                  reflect.ValueOf(aws.Int16Slice),
		"Int16Value":                  reflect.ValueOf(aws.Int16Value),
		"Int16ValueMap":               reflect.ValueOf(aws.Int16ValueMap),
		"Int16ValueSlice":             reflect.ValueOf(aws.Int16ValueSlice),
		"Int32":                       reflect.ValueOf(aws.Int32),
		"Int32Map":                    reflect.ValueOf(aws.Int32Map),
		"Int32Slice":                  reflect.ValueOf(aws.Int32Slice),
		"Int32Value":                  reflect.ValueOf(aws.Int32Value),
		"Int32ValueMap":               reflect.ValueOf(aws.Int32ValueMap),
		"Int32ValueSlice":             reflect.ValueOf(aws.Int32ValueSlice),
		"Int64":                       reflect.ValueOf(aws.Int64),
		"Int64Map":                    reflect.ValueOf(aws.Int64Map),
		"Int64Slice":                  reflect.ValueOf(aws.Int64Slice),
		"Int64Value":                  reflect.ValueOf(aws.Int64Value),
		"Int64ValueMap":               reflect.ValueOf(aws.Int64ValueMap),
		"Int64ValueSlice":             reflect.ValueOf(aws.Int64ValueSlice),
		"Int8":                        reflect.ValueOf(aws.Int8),
		"Int8Map":                     reflect.ValueOf(aws.Int8Map),
		"Int8Slice":                   reflect.ValueOf(aws.Int8Slice),
		"Int8Value":                   reflect.ValueOf(aws.Int8Value),
		"Int8ValueMap":                reflect.ValueOf(aws.Int8ValueMap),
		"Int8ValueSlice":              reflect.ValueOf(aws.Int8ValueSlice),
		"IntMap":                      reflect.ValueOf(aws.IntMap),
		"IntSlice":                    reflect.ValueOf(aws.IntSlice),
		"IntValue":                    reflect.ValueOf(aws.IntValue),
		"IntValueMap":                 reflect.ValueOf(aws.IntValueMap),
		"IntValueSlice":               reflect.ValueOf(aws.IntValueSlice),
		"IsReaderSeekable":            reflect.ValueOf(aws.IsReaderSeekable),
		"LogDebug":                    reflect.ValueOf(aws.LogDebug),
		"LogDebugWithDeprecated":      reflect.ValueOf(aws.LogDebugWithDeprecated),
		"LogDebugWithEventStreamBody": reflect.ValueOf(aws.LogDebugWithEventStreamBody),
		"LogDebugWithHTTPBody":        reflect.ValueOf(aws.LogDebugWithHTTPBody),
		"LogDebugWithRequestErrors":   reflect.ValueOf(aws.LogDebugWithRequestErrors),
		"LogDebugWithRequestRetries":  reflect.ValueOf(aws.LogDebugWithRequestRetries),
		"LogDebugWithSigning":         reflect.ValueOf(aws.LogDebugWithSigning),
		"LogLevel":                    reflect.ValueOf(aws.LogLevel),
		"LogOff":                      reflect.ValueOf(aws.LogOff),
		"MillisecondsTimeValue":       reflect.ValueOf(aws.MillisecondsTimeValue),
		"NewConfig":                   reflect.ValueOf(aws.NewConfig),
		"NewDefaultLogger":            reflect.ValueOf(aws.NewDefaultLogger),
		"NewWriteAtBuffer":            reflect.ValueOf(aws.NewWriteAtBuffer),
		"ReadSeekCloser":              reflect.ValueOf(aws.ReadSeekCloser),
		"SDKName":                     reflect.ValueOf(constant.MakeFromLiteral("\"aws-sdk-go\"", token.STRING, 0)),
		"SDKVersion":                  reflect.ValueOf(constant.MakeFromLiteral("\"1.44.194\"", token.STRING, 0)),
		"SecondsTimeValue":            reflect.ValueOf(aws.SecondsTimeValue),
		"SeekerLen":                   reflect.ValueOf(aws.SeekerLen),
		"SleepWithContext":            reflect.ValueOf(aws.SleepWithContext),
		"String":                      reflect.ValueOf(aws.String),
		"StringMap":                   reflect.ValueOf(aws.StringMap),
		"StringSlice":                 reflect.ValueOf(aws.StringSlice),
		"StringValue":                 reflect.ValueOf(aws.StringValue),
		"StringValueMap":              reflect.ValueOf(aws.StringValueMap),
		"StringValueSlice":            reflect.ValueOf(aws.StringValueSlice),
		"Time":                        reflect.ValueOf(aws.Time),
		"TimeMap":                     reflect.ValueOf(aws.TimeMap),
		"TimeSlice":                   reflect.ValueOf(aws.TimeSlice),
		"TimeUnixMilli":               reflect.ValueOf(aws.TimeUnixMilli),
		"TimeValue":                   reflect.ValueOf(aws.TimeValue),
		"TimeValueMap":                reflect.ValueOf(aws.TimeValueMap),
		"TimeValueSlice":              reflect.ValueOf(aws.TimeValueSlice),
		"URLHostname":                 reflect.ValueOf(aws.URLHostname),
		"Uint":                        reflect.ValueOf(aws.Uint),
		"Uint16":                      reflect.ValueOf(aws.Uint16),
		"Uint16Map":                   reflect.ValueOf(aws.Uint16Map),
		"Uint16Slice":                 reflect.ValueOf(aws.Uint16Slice),
		"Uint16Value":                 reflect.ValueOf(aws.Uint16Value),
		"Uint16ValueMap":              reflect.ValueOf(aws.Uint16ValueMap),
		"Uint16ValueSlice":            reflect.ValueOf(aws.Uint16ValueSlice),
		"Uint32":                      reflect.ValueOf(aws.Uint32),
		"Uint32Map":                   reflect.ValueOf(aws.Uint32Map),
		"Uint32Slice":                 reflect.ValueOf(aws.Uint32Slice),
		"Uint32Value":                 reflect.ValueOf(aws.Uint32Value),
		"Uint32ValueMap":              reflect.ValueOf(aws.Uint32ValueMap),
		"Uint32ValueSlice":            reflect.ValueOf(aws.Uint32ValueSlice),
		"Uint64":                      reflect.ValueOf(aws.Uint64),
		"Uint64Map":                   reflect.ValueOf(aws.Uint64Map),
		"Uint64Slice":                 reflect.ValueOf(aws.Uint64Slice),
		"Uint64Value":                 reflect.ValueOf(aws.Uint64Value),
		"Uint64ValueMap":              reflect.ValueOf(aws.Uint64ValueMap),
		"Uint64ValueSlice":            reflect.ValueOf(aws.Uint64ValueSlice),
		"Uint8":                       reflect.ValueOf(aws.Uint8),
		"Uint8Map":                    reflect.ValueOf(aws.Uint8Map),
		"Uint8Slice":                  reflect.ValueOf(aws.Uint8Slice),
		"Uint8Value":                  reflect.ValueOf(aws.Uint8Value),
		"Uint8ValueMap":               reflect.ValueOf(aws.Uint8ValueMap),
		"Uint8ValueSlice":             reflect.ValueOf(aws.Uint8ValueSlice),
		"UintMap":                     reflect.ValueOf(aws.UintMap),
		"UintSlice":                   reflect.ValueOf(aws.UintSlice),
		"UintValue":                   reflect.ValueOf(aws.UintValue),
		"UintValueMap":                reflect.ValueOf(aws.UintValueMap),
		"UintValueSlice":              reflect.ValueOf(aws.UintValueSlice),
		"UseServiceDefaultRetries":    reflect.ValueOf(constant.MakeFromLiteral("-1", token.INT, 0)),

		// type definitions
		"Config":             reflect.ValueOf((*aws.Config)(nil)),
		"Context":            reflect.ValueOf((*aws.Context)(nil)),
		"JSONValue":          reflect.ValueOf((*aws.JSONValue)(nil)),
		"LogLevelType":       reflect.ValueOf((*aws.LogLevelType)(nil)),
		"Logger":             reflect.ValueOf((*aws.Logger)(nil)),
		"LoggerFunc":         reflect.ValueOf((*aws.LoggerFunc)(nil)),
		"MultiCloser":        reflect.ValueOf((*aws.MultiCloser)(nil)),
		"ReaderSeekerCloser": reflect.ValueOf((*aws.ReaderSeekerCloser)(nil)),
		"RequestRetryer":     reflect.ValueOf((*aws.RequestRetryer)(nil)),
		"WriteAtBuffer":      reflect.ValueOf((*aws.WriteAtBuffer)(nil)),

		// interface wrapper definitions
		"_Context":        reflect.ValueOf((*_github_com_aws_aws_sdk_go_aws_Context)(nil)),
		"_Logger":         reflect.ValueOf((*_github_com_aws_aws_sdk_go_aws_Logger)(nil)),
		"_RequestRetryer": reflect.ValueOf((*_github_com_aws_aws_sdk_go_aws_RequestRetryer)(nil)),
	}
}

// _github_com_aws_aws_sdk_go_aws_Context is an interface wrapper for Context type
type _github_com_aws_aws_sdk_go_aws_Context struct {
	IValue    interface{}
	WDeadline func() (deadline time.Time, ok bool)
	WDone     func() <-chan struct{}
	WErr      func() error
	WValue    func(key any) any
}

func (W _github_com_aws_aws_sdk_go_aws_Context) Deadline() (deadline time.Time, ok bool) {
	return W.WDeadline()
}
func (W _github_com_aws_aws_sdk_go_aws_Context) Done() <-chan struct{} {
	return W.WDone()
}
func (W _github_com_aws_aws_sdk_go_aws_Context) Err() error {
	return W.WErr()
}
func (W _github_com_aws_aws_sdk_go_aws_Context) Value(key any) any {
	return W.WValue(key)
}

// _github_com_aws_aws_sdk_go_aws_Logger is an interface wrapper for Logger type
type _github_com_aws_aws_sdk_go_aws_Logger struct {
	IValue interface{}
	WLog   func(a0 ...interface{})
}

func (W _github_com_aws_aws_sdk_go_aws_Logger) Log(a0 ...interface{}) {
	W.WLog(a0...)
}

// _github_com_aws_aws_sdk_go_aws_RequestRetryer is an interface wrapper for RequestRetryer type
type _github_com_aws_aws_sdk_go_aws_RequestRetryer struct {
	IValue interface{}
}
