// Code generated by 'yaegi extract github.com/alist-org/alist/v3/pkg/cron'. DO NOT EDIT.

package lib

import (
	"github.com/alist-org/alist/v3/pkg/cron"
	"reflect"
)

func init() {
	Symbols["github.com/alist-org/alist/v3/pkg/cron/cron"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewCron": reflect.ValueOf(cron.NewCron),

		// type definitions
		"Cron": reflect.ValueOf((*cron.Cron)(nil)),
	}
}
