name: "Feature request"
description: Feature request
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Please make sure of the following things
      description: You may select more than one, even select all.
      options:
        - label: I have read the [documentation](https://alist.nn.ci).
        - label: I'm sure there are no duplicate issues or discussions.
        - label: I'm sure this feature is not implemented.
        - label: I'm sure it's a reasonable and popular requirement.
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature / 需求描述
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution / 实现思路
      description: |
        Solutions to achieve this requirement.
        实现此需求的解决思路。
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context / 附件
      description: |
        Any other context or screenshots about the feature request here, or information you find helpful.
        相关的任何其他上下文或截图，或者你觉得有帮助的信息